const CardActionTypes = {
    FETCH_CARDS_START: 'FETCH_CARDS_START',
    FETCH_CARDS_SUCCESS: 'FETCH_CARDS_SUCCESS',
    FETCH_CARDS_FAILURE: 'FETCH_CARDS_FAILURE',
    SET_IS_LOADING: 'SET_IS_LOADING',
    ADD_CARD: 'ADD_CARD',
    REMOVE_CARD: 'REMOVE_CARD'
}

export default CardActionTypes;